set ::env(PDK) "sky130A"
set ::env(PDKPATH) "/home/passant/OpenLane/pdks/sky130A"
set ::env(STD_CELL_LIBRARY) "sky130_fd_sc_hd"
set ::env(SCLPATH) "/home/passant/OpenLane/pdks/sky130A/sky130_fd_sc_hd"
set ::env(DESIGN_DIR) "/home/passant/efabless/caravel_user_sram/openlane/SRAM_1024x32"
set ::env(DESIGN_NAME) "SRAM_1024x32"
set ::env(FP_PDN_MULTILAYER) "1"
set ::env(FP_PDN_CORE_RING) "0"
set ::env(VERILOG_FILES) "/home/passant/efabless/caravel_user_sram/openlane/SRAM_1024x32/../../ip/EF_SRAM_1024x32/hdl/ram_controller.v /home/passant/efabless/caravel_user_sram/openlane/SRAM_1024x32/../../ip/EF_SRAM_1024x32/hdl/SRAM_1024x32.v /home/passant/efabless/caravel_user_sram/openlane/SRAM_1024x32/../../ip/EF_SRAM_1024x32/hdl/EFSRAM_1024x32_wrapper.v"
set ::env(SYNTH_DEFINES) "PnR"
set ::env(ERROR_ON_LINTER_ERRORS) "0"
set ::env(CLOCK_PERIOD) "25"
set ::env(CLOCK_PORT) "wb_clk_i"
set ::env(FP_SIZING) "absolute"
set ::env(DIE_AREA) "0.000 0.000 380 435"
set ::env(CORE_AREA) "5.000 5.000 375 430"
set ::env(FP_PIN_ORDER_CFG) "/home/passant/efabless/caravel_user_sram/openlane/SRAM_1024x32/pin_order.cfg"
set ::env(PNR_SDC_FILE) "/home/passant/efabless/caravel_user_sram/openlane/SRAM_1024x32/base.sdc"
set ::env(SIGNOFF_SDC_FILE) "/home/passant/efabless/caravel_user_sram/openlane/SRAM_1024x32/base.sdc"
set ::env(VDD_NETS) "VPWR"
set ::env(GND_NETS) "VGND"
set ::env(VERILOG_FILES_BLACKBOX) "/home/passant/efabless/caravel_user_sram/openlane/SRAM_1024x32/../../ip/EF_SRAM_1024x32/hdl/EFSRAM_01024x032_008_18_stub.v"
set ::env(EXTRA_GDS_FILES) "/home/passant/efabless/caravel_user_sram/openlane/SRAM_1024x32/../../ip/EF_SRAM_1024x32/gds/EFSRAM_1024x32_wrapper.gds"
set ::env(EXTRA_LEFS) "/home/passant/efabless/caravel_user_sram/openlane/SRAM_1024x32/../../ip/EF_SRAM_1024x32/lef/EFSRAM_1024x32_wrapper.lef"
set ::env(EXTRA_LIBS) "/home/passant/efabless/caravel_user_sram/openlane/SRAM_1024x32/../../ip/EF_SRAM_1024x32/lib/EFSRAM_1024x32_wrapper_tt_180V_25C.lib"
set ::env(MACRO_PLACEMENT_CFG) "/home/passant/efabless/caravel_user_sram/openlane/SRAM_1024x32/macro.cfg"
set ::env(FP_PDN_HORIZONTAL_LAYER) "met3"
set ::env(FP_PDN_VERTICAL_LAYER) "met2"
set ::env(RUN_IRDROP_REPORT) "0"
set ::env(FP_PDN_VOFFSET) "5"
set ::env(FP_PDN_HOFFSET) "5"
set ::env(FP_PDN_VWIDTH) "1.76"
set ::env(FP_PDN_HWIDTH) "1.76"
set ::env(FP_PDN_VSPACING) "10"
set ::env(FP_PDN_HSPACING) "10"
set ::env(FP_PDN_VPITCH) "50"
set ::env(FP_PDN_HPITCH) "50"
set ::env(FP_PDN_MACRO_HOOKS) "SRAM_0 VPWR VGND vpwra vgnd,SRAM_0 VPWR VGND vpb vnb,SRAM_0 VPWR VGND vpwrp vgnd,SRAM_0 VPWR VGND vpwrm vgnd"
set ::env(FP_PDN_CFG) "/home/passant/efabless/caravel_user_sram/openlane/SRAM_1024x32/pdn.tcl"
set ::env(QUIT_ON_LINTER_ERRORS) "0"
set ::env(GRT_OBS) "met1 0 40 314 435,met2 0 40 314 435,met3 0 40 314 435,met4 0 40 314 435,met5 0 40 314 435"
set ::env(PL_TARGET_DENSITY) "0.15"
set ::env(PL_TIME_DRIVEN) "0"
set ::env(PL_ROUTABILITY_DRIVEN) "1"
set ::env(GRT_ALLOW_CONGESTION) "1"
set ::env(GRT_ADJUSTMENT) "0"
set ::env(GLB_RESIZER_DESIGN_OPTIMIZATIONS) "1"
set ::env(GLB_RESIZER_TIMING_OPTIMIZATIONS) "1"
set ::env(GRT_REPAIR_ANTENNAS) "0"
set ::env(MAGIC_DRC_USE_GDS) "1"
set ::env(QUIT_ON_MAGIC_DRC) "0"
set ::env(QUIT_ON_KLAYOUT_DRC) "0"
set ::env(MAGIC_EXT_USE_GDS) "1"
set ::env(QUIT_ON_LVS_ERROR) "0"
set ::env(QUIT_ON_TR_DRC) "0"
